server:
  port: ${SERVER_PORT:9000}

spring:

  application:
    name: MykyAuth

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  datasource:
    hikari:
      auto-commit: true
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    driver-class-name: ${DATASOURCE_DRIVER:org.postgresql.Driver}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  security:
    jwt:
      secret: ${JWT_SECRET:secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret}
      exp-min: ${JWT_EXP_MIN:10}
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER:localhost:9000}

  config:
    import: optional:file:.env[.properties]